# Team Name Aliases Configuration
# Maps variant team names to canonical names
# Format: "variant_name": "canonical_name"
# The canonical name should be the official English name of the team

# English Premier League (EPL)
epl:
  "man utd": "manchester united"
  "man united": "manchester united"
  "man u": "manchester united"
  "mufc": "manchester united"
  "utd": "manchester united"
  "man city": "manchester city"
  "city": "manchester city"
  "mcfc": "manchester city"
  "chelsea fc": "chelsea"
  "cfc": "chelsea"
  "liverpool fc": "liverpool"
  "lfc": "liverpool"
  "arsenal fc": "arsenal"
  "the gunners": "arsenal"
  "afc": "arsenal"
  "spurs": "tottenham hotspur"
  "tottenham": "tottenham hotspur"
  "thfc": "tottenham hotspur"
  "newcastle": "newcastle united"
  "nufc": "newcastle united"
  "newcastle utd": "newcastle united"
  "west ham": "west ham united"
  "west ham utd": "west ham united"
  "hammers": "west ham united"
  "brighton": "brighton and hove albion"
  "brighton hove albion": "brighton and hove albion"
  "bha": "brighton and hove albion"
  "aston villa fc": "aston villa"
  "avfc": "aston villa"
  "villa": "aston villa"
  "fulham fc": "fulham"
  "ffc": "fulham"
  "brentford fc": "brentford"
  "crystal palace fc": "crystal palace"
  "palace": "crystal palace"
  "cpfc": "crystal palace"
  "wolves": "wolverhampton wanderers"
  "wolverhampton": "wolverhampton wanderers"
  "wwfc": "wolverhampton wanderers"
  "bournemouth": "afc bournemouth"
  "afcb": "afc bournemouth"
  "forest": "nottingham forest"
  "nffc": "nottingham forest"
  "nottm forest": "nottingham forest"
  "nottingham": "nottingham forest"
  "leeds": "leeds united"
  "everton fc": "everton"
  "efc": "everton"
  "toffees": "everton"
  "luton": "luton town"
  "burnley fc": "burnley"
  "sheffield utd": "sheffield united"
  "sheff utd": "sheffield united"
  "blades": "sheffield united"
  "ipswich": "ipswich town"
  "leicester": "leicester city"
  "foxes": "leicester city"
  "southampton fc": "southampton"
  "saints": "southampton"

# EFL Championship (England)
efl_championship:
  "west brom": "west bromwich albion"
  "west bromwich": "west bromwich albion"
  "wba": "west bromwich albion"
  "baggies": "west bromwich albion"
  "hull": "hull city"
  "the tigers": "hull city"
  "qpr": "queens park rangers"
  "rangers": "queens park rangers"
  "stoke": "stoke city"
  "potters": "stoke city"
  "derby": "derby county"
  "rams": "derby county"
  "norwich": "norwich city"
  "canaries": "norwich city"
  "swansea": "swansea city"
  "swans": "swansea city"
  "coventry": "coventry city"
  "sky blues": "coventry city"
  "middlesbrough fc": "middlesbrough"
  "boro": "middlesbrough"
  "birmingham": "birmingham city"
  "blues": "birmingham city"
  "blackburn": "blackburn rovers"
  "rovers": "blackburn rovers"
  "millwall fc": "millwall"
  "lions": "millwall"
  "watford fc": "watford"
  "hornets": "watford"
  "preston": "preston north end"
  "pne": "preston north end"
  "bristol city fc": "bristol city"
  "robins": "bristol city"
  "charlton": "charlton athletic"
  "addicks": "charlton athletic"
  "oxford": "oxford united"
  "portsmouth fc": "portsmouth"
  "pompey": "portsmouth"
  "sheff wed": "sheffield wednesday"
  "wednesday": "sheffield wednesday"
  "owls": "sheffield wednesday"
  "wrexham afc": "wrexham"

# La Liga (Spain)
la_liga:
  "real madrid cf": "real madrid"
  "madrid": "real madrid"
  "los blancos": "real madrid"
  "barca": "barcelona"
  "fc barcelona": "barcelona"
  "blaugrana": "barcelona"
  "atletico madrid": "atletico de madrid"
  "atleti": "atletico de madrid"
  "atletico": "atletico de madrid"
  "atlético madrid": "atletico de madrid"
  "atlético de madrid": "atletico de madrid"
  "sevilla fc": "sevilla"
  "real betis balompie": "real betis"
  "betis": "real betis"
  "real sociedad de futbol": "real sociedad"
  "la real": "real sociedad"
  "villarreal cf": "villarreal"
  "yellow submarine": "villarreal"
  "athletic bilbao": "athletic club"
  "athletic club bilbao": "athletic club"
  "valencia cf": "valencia"
  "osasuna": "ca osasuna"
  "celta vigo": "celta de vigo"
  "celta": "celta de vigo"
  "rayo vallecano de madrid": "rayo vallecano"
  "rayo": "rayo vallecano"
  "getafe cf": "getafe"
  "alaves": "deportivo alaves"
  "alavés": "deportivo alaves"
  "deportivo alavés": "deportivo alaves"
  "mallorca": "rcd mallorca"
  "real mallorca": "rcd mallorca"
  "girona fc": "girona"
  "las palmas": "ud las palmas"
  "almeria": "ud almeria"
  "cadiz": "cadiz cf"
  "cádiz": "cadiz cf"
  "granada": "granada cf"
  "real valladolid cf": "real valladolid"
  "valladolid": "real valladolid"
  "espanyol": "rcd espanyol"
  "leganes": "cd leganes"
  "leganés": "cd leganes"

# Serie A (Italy)
serie_a:
  "inter": "inter milan"
  "inter milano": "inter milan"
  "internazionale": "inter milan"
  "fc internazionale milano": "inter milan"
  "ac milan": "milan"
  "rossoneri": "milan"
  "juve": "juventus"
  "juventus fc": "juventus"
  "old lady": "juventus"
  "napoli": "ssc napoli"
  "i partenopei": "ssc napoli"
  "roma": "as roma"
  "giallorossi": "as roma"
  "lazio": "ss lazio"
  "fiorentina": "acf fiorentina"
  "viola": "acf fiorentina"
  "atalanta bc": "atalanta"
  "la dea": "atalanta"
  "torino fc": "torino"
  "toro": "torino"
  "bologna fc": "bologna"
  "udinese calcio": "udinese"
  "sassuolo": "us sassuolo"
  "empoli fc": "empoli"
  "verona": "hellas verona"
  "hellas": "hellas verona"
  "lecce": "us lecce"
  "cagliari calcio": "cagliari"
  "genoa cfc": "genoa"
  "monza": "ac monza"
  "frosinone calcio": "frosinone"
  "salernitana": "us salernitana 1919"
  "parma calcio": "parma"
  "como 1907": "como"
  "venezia fc": "venezia"

# Bundesliga (Germany)
bundesliga:
  "bayern": "bayern munich"
  "bayern munchen": "bayern munich"
  "bayern münchen": "bayern munich"
  "fc bayern": "bayern munich"
  "fcb": "bayern munich"
  "bvb": "borussia dortmund"
  "dortmund": "borussia dortmund"
  "borussia": "borussia dortmund"
  "rb leipzig": "leipzig"
  "rasenballsport leipzig": "leipzig"
  "leverkusen": "bayer leverkusen"
  "bayer 04 leverkusen": "bayer leverkusen"
  "gladbach": "borussia monchengladbach"
  "borussia mönchengladbach": "borussia monchengladbach"
  "bmg": "borussia monchengladbach"
  "frankfurt": "eintracht frankfurt"
  "eintracht": "eintracht frankfurt"
  "sge": "eintracht frankfurt"
  "wolfsburg": "vfl wolfsburg"
  "hoffenheim": "tsg hoffenheim"
  "tsg 1899 hoffenheim": "tsg hoffenheim"
  "freiburg": "sc freiburg"
  "koln": "fc koln"
  "köln": "fc koln"
  "fc cologne": "fc koln"
  "cologne": "fc koln"
  "mainz": "mainz 05"
  "fsv mainz": "mainz 05"
  "mainz 05": "mainz 05"
  "augsburg": "fc augsburg"
  "stuttgart": "vfb stuttgart"
  "werder": "werder bremen"
  "bremen": "werder bremen"
  "sv werder bremen": "werder bremen"
  "union": "union berlin"
  "fc union berlin": "union berlin"
  "hertha": "hertha berlin"
  "hertha bsc": "hertha berlin"
  "bochum": "vfl bochum"
  "heidenheim": "fc heidenheim"
  "1. fc heidenheim 1846": "fc heidenheim"
  "darmstadt": "sv darmstadt 98"
  "sv darmstadt": "sv darmstadt 98"
  "st pauli": "fc st pauli"
  "fc st. pauli": "fc st pauli"
  "holstein kiel": "kiel"

# Ligue 1 (France)
ligue_1:
  "psg": "paris saint germain"
  "paris sg": "paris saint germain"
  "paris saint-germain": "paris saint germain"
  "monaco": "as monaco"
  "lyon": "olympique lyonnais"
  "ol": "olympique lyonnais"
  "olympique lyon": "olympique lyonnais"
  "marseille": "olympique de marseille"
  "om": "olympique de marseille"
  "olympique marseille": "olympique de marseille"
  "lille": "lille osc"
  "losc": "lille osc"
  "losc lille": "lille osc"
  "nice": "ogc nice"
  "lens": "rc lens"
  "racing club de lens": "rc lens"
  "rennes": "stade rennais"
  "stade rennais fc": "stade rennais"
  "strasbourg": "rc strasbourg"
  "rc strasbourg alsace": "rc strasbourg"
  "nantes": "fc nantes"
  "brest": "stade brestois"
  "stade brestois 29": "stade brestois"
  "reims": "stade de reims"
  "montpellier": "montpellier hsc"
  "mhsc": "montpellier hsc"
  "toulouse": "toulouse fc"
  "tfc": "toulouse fc"
  "lorient": "fc lorient"
  "clermont": "clermont foot"
  "clermont foot 63": "clermont foot"
  "metz": "fc metz"
  "le havre": "le havre ac"
  "hac": "le havre ac"
  "saint-etienne": "as saint etienne"
  "st etienne": "as saint etienne"
  "asse": "as saint etienne"
  "angers": "angers sco"
  "sco angers": "angers sco"
  "auxerre": "aj auxerre"

# MLS (Major League Soccer - USA)
mls:
  "la galaxy": "los angeles galaxy"
  "galaxy": "los angeles galaxy"
  "lafc": "los angeles fc"
  "inter miami": "inter miami cf"
  "miami": "inter miami cf"
  "atlanta": "atlanta united"
  "atl utd": "atlanta united"
  "atlanta utd": "atlanta united"
  "seattle": "seattle sounders"
  "sounders": "seattle sounders"
  "portland": "portland timbers"
  "timbers": "portland timbers"
  "nycfc": "new york city fc"
  "nyc fc": "new york city fc"
  "new york city": "new york city fc"
  "red bulls": "new york red bulls"
  "nyrb": "new york red bulls"
  "rbny": "new york red bulls"
  "columbus": "columbus crew"
  "crew": "columbus crew"
  "toronto": "toronto fc"
  "tfc": "toronto fc"
  "philadelphia": "philadelphia union"
  "union": "philadelphia union"
  "dc": "dc united"
  "d.c. united": "dc united"
  "dc utd": "dc united"
  "sporting kc": "sporting kansas city"
  "skc": "sporting kansas city"
  "orlando": "orlando city"
  "ocsc": "orlando city"
  "charlotte": "charlotte fc"
  "nashville": "nashville sc"
  "houston": "houston dynamo"
  "dynamo": "houston dynamo"
  "fc dallas": "dallas"
  "austin": "austin fc"
  "minnesota": "minnesota united"
  "mnufc": "minnesota united"
  "san jose": "san jose earthquakes"
  "quakes": "san jose earthquakes"
  "colorado": "colorado rapids"
  "rapids": "colorado rapids"
  "real salt lake": "salt lake"
  "rsl": "salt lake"
  "vancouver": "vancouver whitecaps"
  "whitecaps": "vancouver whitecaps"
  "montreal": "cf montreal"
  "cf montréal": "cf montreal"
  "impact": "cf montreal"
  "new england": "new england revolution"
  "revs": "new england revolution"
  "chicago": "chicago fire"
  "fire": "chicago fire"
  "cincinnati": "fc cincinnati"
  "fcc": "fc cincinnati"
  "st louis": "st louis city sc"
  "st. louis city": "st louis city sc"
  "stl city": "st louis city sc"

# Liga MX (Mexico)
liga_mx:
  "america": "club america"
  "club américa": "club america"
  "aguilas": "club america"
  "guadalajara": "chivas guadalajara"
  "chivas": "chivas guadalajara"
  "cd guadalajara": "chivas guadalajara"
  "tigres": "tigres uanl"
  "tigres uanl": "tigres uanl"
  "monterrey": "cf monterrey"
  "rayados": "cf monterrey"
  "cruz azul": "cruz azul"
  "la maquina": "cruz azul"
  "pumas": "pumas unam"
  "unam": "pumas unam"
  "leon": "club leon"
  "club león": "club leon"
  "santos": "santos laguna"
  "toluca": "deportivo toluca"
  "pachuca": "cf pachuca"
  "tuzos": "cf pachuca"
  "atlas": "atlas fc"
  "rojinegros": "atlas fc"
  "necaxa": "club necaxa"
  "rayos": "club necaxa"
  "san luis": "atletico san luis"
  "atlético san luis": "atletico san luis"
  "puebla": "club puebla"
  "franja": "club puebla"
  "tijuana": "club tijuana"
  "xolos": "club tijuana"
  "queretaro": "queretaro fc"
  "gallos": "queretaro fc"
  "mazatlan": "mazatlan fc"
  "mazatlán fc": "mazatlan fc"
  "juarez": "fc juarez"
  "fc juárez": "fc juarez"

# Global fallbacks (common patterns across all leagues)
global:
  # Common suffixes/prefixes to strip
  "fc": ""
  "cf": ""
  "sc": ""
  "afc": ""
  "fk": ""
  "ac": ""
  "ssc": ""
  "rcd": ""
  "cd": ""
  "vfb": ""
  "vfl": ""
  "sv": ""
  "fsv": ""
  "1.": ""
  "1899": ""
  "1846": ""
  "1919": ""
  "1907": ""
  "04": ""
  "05": ""
  "98": ""
